---
title: "MXB262 Project 2"
author: "Lok Sze Victoria Chen"
date: "16/05/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#install.packages("gtrendsR")
 
# load the libraries
library(dplyr)
library(ggplot2)
library(gtrendsR)
library(maps)
```

```{r}
#define the keywords
keywords=c("Paris","New York","Barcelona")

#set the geographic area: DE = Germany
country=c('DE')

#set the time window
time=("2017-01-01 2018-08-27")

#set channels 
channel='web'

trends = gtrends(keywords, gprop =channel,geo=country, time = time )
#select only interst over time 
time_trend=trends$interest_over_time
head(time_trend)

plot<-ggplot(data=time_trend, aes(x=date, y=hits,group=keyword,col=keyword))+
        geom_line()+xlab('Time')+ylab('Relative Interest')+ theme_bw()+
        theme(legend.title = element_blank(),legend.position="bottom",legend.text=element_text(size=12))+ggtitle("Google Search Volume")
plot
```

